version: "3.9"

services:
  app:
    container_name: devsecops-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - sonarqube
    networks:
      - devsecops-net

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db
    networks:
      - devsecops-net

  sonar-db:
    container_name: sonar-db
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_data:/var/lib/postgresql/data
    networks:
      - devsecops-net

networks:
  devsecops-net:

volumes:
  sonar_data:
