version: '3.8'

services:
  sonar-db:
    image: postgres:12
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      sonar-db:
        condition: service_healthy
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-app
    ports:
      - "3000:3000"

volumes:
  sonar_db_data:
